version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs: 

  Gravitee_job2:
    docker:
      - image: 'cimg/node:16.3.0'
    environment:
      JOB_NAME: 'test2'
    steps:
      - run:
          name: "What is the name of job?"
          command: |
                    echo "The name of the job is : [${JOB_NAME}]"
                    sleep 20s
  Gravitee_job:
    docker:
      - image: 'cimg/node:16.3.0'
    environment:
      JOB_NAME: 'test'
    steps:
      - run:
          name: "What is the name of job?"
          command: |
                    echo "The name of the job is : [${JOB_NAME}]"
    
 
  Hakim_hello:
    docker:
      - image: 'cimg/node:16.3.0'
    environment:
      HAKIM_NAME: 'Louati'
    steps:
      - run:
          name: "What is the name of Hakim?"
          command: |
                    echo "The name of Hakim is : [${HAKIM_NAME}]"
      - run:
          name: "test step?"
          command: |
                    echo "the test step is : [${HAKIM_NAME}]"
                   
workflows:
  Gravitee_test:
    jobs:
      - Gravitee_job2
      - Gravitee_job
      - Hakim_hello:
          requires:
            - Gravitee_job
      - heroku/deploy-via-git:
          requires: 
            - Hakim_hello
            - Gravitee_job2
      
