version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs: 
  Hakim_hello:
    docker:
      - image: 'cimg/node:16.3.0'
    environment:
      HAKIM_NAME: 'Louati'
    steps:
      - run:
          name: "What is the name of Hakim?"
          command: |
                    echo "The name of Hakim is : [${HAKIM_NAME}]"
      - run:
          name: "test step?"
          command: |
                    echo "the test step is : [${HAKIM_NAME}]"
                    exit 1
workflows:
  Gravitee_test:
    jobs:
      - Hakim_hello
      - heroku/deploy-via-git:
          requires: 
            - Hakim_hello
